name: Generate & Commit HTML Pages

# รอ event จาก n8n (repository_dispatch)
on:
  repository_dispatch:
    types: [generate-pages]

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 1. เช็คเอาท์โค้ดจาก repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ติดตั้ง Node.js และ dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # 3. เซฟ payload จาก n8n (ถ้าต้องการใช้)
      - name: Save payload
        run: |
          cat << 'EOF' > data.json
          ${{ toJson(github.event.client_payload.data) }}
          EOF

      # 4. รันสคริปต์ generateHTML
      - name: Run render.js
        run: node render.js

      # 5. Commit และ Push หน้า HTML ที่สร้างใหม่
      - name: Commit generated pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pages/
          git commit -m "🔄 Generate HTML pages via GitHub Actions"
          git push
        env:
          # จะใช้ token ที่ GitHub ให้มาโดยอัตโนมัติ
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
