name: Generate & Commit HTML Pages

# รอ event จาก n8n (repository_dispatch)
on:
  repository_dispatch:
    types: [generate-pages]

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # ← แทนที่บล็อก “Save payload” แบบ bash → ทำเป็น GitHub Script
      - name: Write payload to data.json
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            // github.event.client_payload.data คือ array ของ projects ที่ส่งมา
            fs.writeFileSync(
              'data.json',
              JSON.stringify(github.event.client_payload.data),
              'utf-8'
            );

      - name: Run render.js to generate HTML
        run: node render.js

      - name: Commit generated pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pages/
          git commit -m "🔄 Generate pages via GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

