name: Generate & Commit HTML Pages

on:
  repository_dispatch:
    types: [generate-pages]

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Write payload to data.json
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const clientPayload = context.payload.client_payload;
            if (!clientPayload) {
              throw new Error('❌ No client_payload found in dispatch event');
            }
            fs.writeFileSync(
              'data.json',
              JSON.stringify(clientPayload.data, null, 2),
              'utf-8'
            );

      - name: Run render.js to generate HTML
        run: node render.js

      - name: Commit generated pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pages/

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "🔄 Generate pages via GitHub Actions"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

